schedule:
  "30 * * * *":
    - lottery broadcast
  "* * * * *":
    - say test
    - give @a diamond

messages:
  noPermission: '&cNincs jogod ehhez.'
  usage: '&bHasználat: /croncommand reload'
  reloaded: '&bPlugin sikeresen újratöltve'
