name: CronCommand
version: ${version}
main: com.danifoldi.croncommand.CronCommand
authors:
  - DaniFoldi
  - HgeX
description: Run commands at specified cron times
api-version: 1.13

commands:
  croncommand:
    description: Used to reload the plugin

permissions:
  croncommand.reload:
    description: Permission to reload the plugin