name: Publish to repository

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :shadowJar
    - name: Detect version
      run: |
       cd build/libs/
       $VERSION=grep -oE "[0-9]+(\.[0-9]+)+(-[a-zA-Z0-9])?"
       export VERSION
       echo "::set-env name=VERSION::$VERSION"
    - name: Publish to Nexus
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://repo.danifoldi.com
        username: ${{ secrets.repo_username }}
        password: ${{ secrets.repo_password }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=com.danifoldi artifactId=croncommand version=$VERSION
        assets: extension=jar
        filename: ./build/libs/CronCommand-$VERSION.jar
